import sys
from PyQt5.QtWidgets import (QDialog,QLabel,QApplication,QVBoxLayout,
                             QHBoxLayout)
import qdarkstyle
from PyQt5.QtGui import QIcon,QPixmap,QFont
from PyQt5.QtSql import QSqlQuery,QSqlDatabase


class PetDetailDialog(QDialog):
    def __init__(self,PetId):
        super(PetDetailDialog,self).__init__()
        self.str = PetId
        self.resize(500, 700)
        self.setWindowTitle("myPet——宠物详情")
        self.setWindowIcon(QIcon("./images/icon.png"))
        self.initUI()

    def initUI(self):
        self.db = QSqlDatabase.addDatabase("QSQLITE")
        self.db.setDatabaseName('./db/myPet.db')
        self.db.open()
        self.query = QSqlQuery()
        sql = "select pet.PetId,PetStatus,UserMail,PetImage," \
              "PetType,FromLocation,FromTime,StayLocation " \
              "from user,pet,pet_detail " \
              "where user.UserId = pet.ReleaseUserId " \
              "and pet.PetId = pet_detail.PetId " \
              "and pet.PetId = '%s'" %(self.str)
        self.query.exec_(sql)
        self.query.next()
        id = self.query.value(0)
        status = self.query.value(1)
        mail= self.query.value(2)
        imagePath = self.query.value(3)
        type = self.query.value(4)
        froml = self.query.value(5)
        fromt = self.query.value(6)
        stayl = self.query.value(7)

        self.labeltitle = QLabel(self)
        self.imagetitle = QPixmap()
        self.imagetitle.load(imagePath)
        self.labeltitle.setFixedSize(500, 350)
        self.labeltitle.setPixmap(self.imagetitle.scaled(self.labeltitle.width(), self.labeltitle.height()))
        self.h1box = QHBoxLayout()
        self.h1box.addStretch(1)
        self.h1box.addWidget(self.labeltitle)
        self.h1box.addStretch(1)

        self.idlabel = QLabel()
        self.idlabel.setText('备案编号：')
        self.idlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.idlabel_ = QLabel()
        self.idlabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.idlabel_.setText(id)
        self.h2box = QHBoxLayout()
        self.h2box.addStretch(1)
        self.h2box.addWidget(self.idlabel)
        self.h2box.addWidget(self.idlabel_)
        self.h2box.addStretch(1)

        self.typelabel = QLabel()
        self.typelabel.setText('动物种类：')
        self.typelabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.typelabel_ = QLabel()
        self.typelabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.typelabel_.setText(type)
        self.statuslabel = QLabel()
        self.statuslabel.setText('当前状态：')
        self.statuslabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.statuslabel_ = QLabel()
        self.statuslabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.statuslabel_.setText(status)
        self.h3box = QHBoxLayout()
        self.h3box.addStretch(1)
        self.h3box.addWidget(self.typelabel)
        self.h3box.addWidget(self.typelabel_)
        self.h3box.addStretch(1)
        self.h3box.addWidget(self.statuslabel)
        self.h3box.addWidget(self.statuslabel_)
        self.h3box.addStretch(1)

        self.fromllabel = QLabel()
        self.fromllabel.setText('发现地点：')
        self.fromllabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.fromllabel_ = QLabel()
        self.fromllabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.fromllabel_.setText(froml)
        self.fromtlabel = QLabel()
        self.fromtlabel.setText('发现时间：')
        self.fromtlabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.fromtlabel_ = QLabel()
        self.fromtlabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.fromtlabel_.setText(fromt)
        self.h4box = QHBoxLayout()
        self.h4box.addStretch(1)
        self.h4box.addWidget(self.fromllabel)
        self.h4box.addWidget(self.fromllabel_)
        self.h4box.addStretch(1)
        self.h4box.addWidget(self.fromtlabel)
        self.h4box.addWidget(self.fromtlabel_)
        self.h4box.addStretch(1)

        self.staylabel = QLabel()
        self.staylabel.setText('收留地点：')
        self.staylabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.staylabel_ = QLabel()
        self.staylabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.staylabel_.setText(stayl)
        self.h5box = QHBoxLayout()
        self.h5box.addStretch(1)
        self.h5box.addWidget(self.staylabel)
        self.h5box.addWidget(self.staylabel_)
        self.h5box.addStretch(1)

        self.maillabel = QLabel()
        self.maillabel.setText('发现人邮箱')
        self.maillabel.setFont(QFont("苏新诗柳楷繁", 13))
        self.maillabel_ = QLabel()
        self.maillabel_.setFont(QFont("苏新诗柳楷繁", 13))
        self.maillabel_.setText(mail)
        self.h6box = QHBoxLayout()
        self.h6box.addStretch(1)
        self.h6box.addWidget(self.maillabel)
        self.h6box.addWidget(self.maillabel_)
        self.h6box.addStretch(1)

        self.vbox = QVBoxLayout()
        self.vbox.addLayout(self.h1box)
        self.vbox.addStretch(1)
        self.vbox.addLayout(self.h2box)
        self.vbox.addStretch(1)
        self.vbox.addLayout(self.h3box)
        self.vbox.addStretch(1)
        self.vbox.addLayout(self.h4box)
        self.vbox.addStretch(1)
        self.vbox.addLayout(self.h5box)
        self.vbox.addStretch(1)
        self.vbox.addLayout(self.h6box)
        self.vbox.addStretch(1)
        self.setLayout(self.vbox)

if __name__ == '__main__':
    app = QApplication(sys.argv)
    app.setStyleSheet(qdarkstyle.load_stylesheet_pyqt5())
    aboutWindow = PetDetailDialog("p1811226061")
    aboutWindow.show()
    sys.exit(app.exec_())